/* Generated by Yosys 0.35+29 (git sha1 ab6c1d368, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* dynports =  1  *)
(* hdlname = "\\cla" *)
(* src = "cla/cla.sv:1.1-48.10" *)
module \$paramod\cla\WIDTH=s32'00000000000000000000000000010000 (a, b, z);
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _000_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _001_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _002_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _003_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _004_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _005_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _006_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _007_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _008_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _009_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _010_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _011_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _012_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _013_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _014_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _015_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _016_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _017_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _018_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _019_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _020_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _021_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _022_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _023_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _024_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _025_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _026_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _027_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _028_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _029_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _030_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _031_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _032_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _033_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _034_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _035_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _036_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _037_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _038_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _039_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _040_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _041_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _042_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _043_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _044_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _045_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _046_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _047_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _048_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _049_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _050_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _051_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _052_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _053_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _054_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _055_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _056_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _057_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _058_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _059_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _060_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _061_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _062_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _063_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _064_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _065_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _066_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _067_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _068_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _069_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _070_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _071_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _072_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _073_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _074_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _075_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _076_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _077_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _078_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _079_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _080_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _081_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _082_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _083_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _084_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _085_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _086_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _087_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _088_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _089_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _090_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _091_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _092_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _093_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _094_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _095_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _096_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _097_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _098_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _099_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _100_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _101_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _102_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _103_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _104_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _105_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _106_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _107_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _108_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _109_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _110_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _111_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _112_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _113_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _114_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _115_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _116_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _117_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _118_;
  (* src = "cla/cla.sv:30.33-30.49" *)
  wire _119_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _120_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _121_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _122_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _123_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _124_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _125_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _126_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _127_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _128_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _129_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _130_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _131_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _132_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _133_;
  (* src = "cla/cla.sv:33.38-33.53" *)
  wire _134_;
  (* src = "cla/cla.sv:38.28-38.40" *)
  wire _135_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _136_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _137_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _138_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _139_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _140_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _141_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _142_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _143_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _144_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _145_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _146_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _147_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _148_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _149_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _150_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _151_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _152_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _153_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _154_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _155_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _156_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _157_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _158_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _159_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _160_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _161_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _162_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _163_;
  (* src = "cla/cla.sv:33.30-33.54" *)
  wire _164_;
  (* src = "cla/cla.sv:33.30-33.61" *)
  wire _165_;
  (* src = "cla/cla.sv:38.20-38.41" *)
  wire _166_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _167_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _168_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _169_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _170_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _171_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _172_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _173_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _174_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _175_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _176_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _177_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _178_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _179_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _180_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _181_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _182_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _183_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _184_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _185_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _186_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _187_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _188_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _189_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _190_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _191_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _192_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _193_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _194_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _195_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _196_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _197_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _198_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _199_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _200_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _201_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _202_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _203_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _204_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _205_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _206_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _207_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _208_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _209_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _210_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _211_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _212_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _213_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _214_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _215_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _216_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _217_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _218_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _219_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _220_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _221_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _222_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _223_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _224_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _225_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _226_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _227_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _228_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _229_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _230_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _231_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _232_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _233_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _234_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _235_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _236_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _237_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _238_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _239_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _240_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _241_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _242_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _243_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _244_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _245_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _246_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _247_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _248_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _249_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _250_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _251_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _252_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _253_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _254_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _255_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _256_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _257_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _258_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _259_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _260_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _261_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _262_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _263_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _264_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _265_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _266_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _267_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _268_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _269_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _270_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _271_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _272_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _273_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _274_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _275_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _276_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _277_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _278_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _279_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _280_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _281_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _282_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _283_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _284_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _285_;
  (* src = "cla/cla.sv:30.40-30.49" *)
  wire _286_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _287_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _288_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _289_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _290_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _291_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _292_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _293_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _294_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _295_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _296_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _297_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _298_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _299_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _300_;
  (* src = "cla/cla.sv:33.46-33.53" *)
  wire _301_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _302_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _303_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _304_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _305_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _306_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _307_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _308_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _309_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _310_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _311_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _312_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _313_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _314_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _315_;
  (* src = "cla/cla.sv:33.57-33.61" *)
  wire _316_;
  (* src = "cla/cla.sv:2.29-2.30" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "cla/cla.sv:3.29-3.30" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "cla/cla.sv:8.23-8.25" *)
  wire [16:0] ci;
  (* src = "cla/cla.sv:10.23-10.24" *)
  wire [15:0] g;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [9:0] \generate_carry_lookaheads[10].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [10:0] \generate_carry_lookaheads[11].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [11:0] \generate_carry_lookaheads[12].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [12:0] \generate_carry_lookaheads[13].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [13:0] \generate_carry_lookaheads[14].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [14:0] \generate_carry_lookaheads[15].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire \generate_carry_lookaheads[1].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [1:0] \generate_carry_lookaheads[2].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [2:0] \generate_carry_lookaheads[3].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [3:0] \generate_carry_lookaheads[4].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [4:0] \generate_carry_lookaheads[5].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [5:0] \generate_carry_lookaheads[6].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [6:0] \generate_carry_lookaheads[7].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [7:0] \generate_carry_lookaheads[8].tmp ;
  (* src = "cla/cla.sv:28.26-28.29" *)
  wire [8:0] \generate_carry_lookaheads[9].tmp ;
  (* src = "cla/cla.sv:9.23-9.24" *)
  wire [15:0] p;
  (* src = "cla/cla.sv:5.29-5.30" *)
  output [16:0] z;
  wire [16:0] z;
  assign _005_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _286_;
  assign _000_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _167_;
  assign _001_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _168_;
  assign _002_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _169_;
  assign _003_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _170_;
  assign _004_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _171_;
  assign _006_ = g[5] & (* src = "cla/cla.sv:30.33-30.49" *) _172_;
  assign _007_ = g[6] & (* src = "cla/cla.sv:30.33-30.49" *) _173_;
  assign _008_ = g[7] & (* src = "cla/cla.sv:30.33-30.49" *) _174_;
  assign _009_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _175_;
  assign _010_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _176_;
  assign _011_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _177_;
  assign _012_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _178_;
  assign _013_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _179_;
  assign _014_ = g[5] & (* src = "cla/cla.sv:30.33-30.49" *) _180_;
  assign _015_ = g[6] & (* src = "cla/cla.sv:30.33-30.49" *) _181_;
  assign _016_ = g[7] & (* src = "cla/cla.sv:30.33-30.49" *) _182_;
  assign _017_ = g[8] & (* src = "cla/cla.sv:30.33-30.49" *) _183_;
  assign _018_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _184_;
  assign _019_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _185_;
  assign _020_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _186_;
  assign _021_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _187_;
  assign _022_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _188_;
  assign _023_ = g[5] & (* src = "cla/cla.sv:30.33-30.49" *) _189_;
  assign _024_ = g[6] & (* src = "cla/cla.sv:30.33-30.49" *) _190_;
  assign _025_ = g[7] & (* src = "cla/cla.sv:30.33-30.49" *) _191_;
  assign _026_ = g[8] & (* src = "cla/cla.sv:30.33-30.49" *) _192_;
  assign _027_ = g[9] & (* src = "cla/cla.sv:30.33-30.49" *) _193_;
  assign _033_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _195_;
  assign _028_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _194_;
  assign _029_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _196_;
  assign _030_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _197_;
  assign _031_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _198_;
  assign _032_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _199_;
  assign _034_ = g[5] & (* src = "cla/cla.sv:30.33-30.49" *) _200_;
  assign _035_ = g[6] & (* src = "cla/cla.sv:30.33-30.49" *) _201_;
  assign _036_ = g[7] & (* src = "cla/cla.sv:30.33-30.49" *) _202_;
  assign _037_ = g[8] & (* src = "cla/cla.sv:30.33-30.49" *) _203_;
  assign _038_ = g[9] & (* src = "cla/cla.sv:30.33-30.49" *) _204_;
  assign _042_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _206_;
  assign _039_ = g[10] & (* src = "cla/cla.sv:30.33-30.49" *) _205_;
  assign _040_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _207_;
  assign _041_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _208_;
  assign _043_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _209_;
  assign _044_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _210_;
  assign _045_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _211_;
  assign _046_ = g[5] & (* src = "cla/cla.sv:30.33-30.49" *) _212_;
  assign _047_ = g[6] & (* src = "cla/cla.sv:30.33-30.49" *) _213_;
  assign _048_ = g[7] & (* src = "cla/cla.sv:30.33-30.49" *) _214_;
  assign _049_ = g[8] & (* src = "cla/cla.sv:30.33-30.49" *) _215_;
  assign _050_ = g[9] & (* src = "cla/cla.sv:30.33-30.49" *) _216_;
  assign _051_ = g[10] & (* src = "cla/cla.sv:30.33-30.49" *) _217_;
  assign _052_ = g[11] & (* src = "cla/cla.sv:30.33-30.49" *) _218_;
  assign _053_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _219_;
  assign _054_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _220_;
  assign _055_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _221_;
  assign _056_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _222_;
  assign _057_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _223_;
  assign _058_ = g[5] & (* src = "cla/cla.sv:30.33-30.49" *) _224_;
  assign _059_ = g[6] & (* src = "cla/cla.sv:30.33-30.49" *) _225_;
  assign _060_ = g[7] & (* src = "cla/cla.sv:30.33-30.49" *) _226_;
  assign _061_ = g[8] & (* src = "cla/cla.sv:30.33-30.49" *) _227_;
  assign _062_ = g[9] & (* src = "cla/cla.sv:30.33-30.49" *) _228_;
  assign _063_ = g[10] & (* src = "cla/cla.sv:30.33-30.49" *) _229_;
  assign _064_ = g[11] & (* src = "cla/cla.sv:30.33-30.49" *) _230_;
  assign _065_ = g[12] & (* src = "cla/cla.sv:30.33-30.49" *) _231_;
  assign _066_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _232_;
  assign _067_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _233_;
  assign _073_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _234_;
  assign _068_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _235_;
  assign _069_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _236_;
  assign _070_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _237_;
  assign _071_ = g[5] & (* src = "cla/cla.sv:30.33-30.49" *) _238_;
  assign _072_ = g[6] & (* src = "cla/cla.sv:30.33-30.49" *) _239_;
  assign _074_ = g[7] & (* src = "cla/cla.sv:30.33-30.49" *) _240_;
  assign _075_ = g[8] & (* src = "cla/cla.sv:30.33-30.49" *) _241_;
  assign _076_ = g[9] & (* src = "cla/cla.sv:30.33-30.49" *) _242_;
  assign _077_ = g[10] & (* src = "cla/cla.sv:30.33-30.49" *) _243_;
  assign _078_ = g[11] & (* src = "cla/cla.sv:30.33-30.49" *) _244_;
  assign _081_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _245_;
  assign _079_ = g[12] & (* src = "cla/cla.sv:30.33-30.49" *) _246_;
  assign _080_ = g[13] & (* src = "cla/cla.sv:30.33-30.49" *) _247_;
  assign _082_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _248_;
  assign _083_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _249_;
  assign _084_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _250_;
  assign _085_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _251_;
  assign _086_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _252_;
  assign _092_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _254_;
  assign _087_ = g[5] & (* src = "cla/cla.sv:30.33-30.49" *) _253_;
  assign _088_ = g[6] & (* src = "cla/cla.sv:30.33-30.49" *) _255_;
  assign _089_ = g[7] & (* src = "cla/cla.sv:30.33-30.49" *) _256_;
  assign _090_ = g[8] & (* src = "cla/cla.sv:30.33-30.49" *) _257_;
  assign _091_ = g[9] & (* src = "cla/cla.sv:30.33-30.49" *) _258_;
  assign _093_ = g[10] & (* src = "cla/cla.sv:30.33-30.49" *) _259_;
  assign _094_ = g[11] & (* src = "cla/cla.sv:30.33-30.49" *) _260_;
  assign _095_ = g[12] & (* src = "cla/cla.sv:30.33-30.49" *) _261_;
  assign _096_ = g[13] & (* src = "cla/cla.sv:30.33-30.49" *) _262_;
  assign _097_ = g[14] & (* src = "cla/cla.sv:30.33-30.49" *) _263_;
  assign _098_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _264_;
  assign _099_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _265_;
  assign _100_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _266_;
  assign _101_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _267_;
  assign _102_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _268_;
  assign _103_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _269_;
  assign _104_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _270_;
  assign _105_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _271_;
  assign _106_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _272_;
  assign _107_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _273_;
  assign _108_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _274_;
  assign _109_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _275_;
  assign _110_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _276_;
  assign _111_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _277_;
  assign _112_ = g[5] & (* src = "cla/cla.sv:30.33-30.49" *) _278_;
  assign _113_ = g[0] & (* src = "cla/cla.sv:30.33-30.49" *) _279_;
  assign _114_ = g[1] & (* src = "cla/cla.sv:30.33-30.49" *) _280_;
  assign _115_ = g[2] & (* src = "cla/cla.sv:30.33-30.49" *) _281_;
  assign _116_ = g[3] & (* src = "cla/cla.sv:30.33-30.49" *) _282_;
  assign _117_ = g[4] & (* src = "cla/cla.sv:30.33-30.49" *) _283_;
  assign _118_ = g[5] & (* src = "cla/cla.sv:30.33-30.49" *) _284_;
  assign _119_ = g[6] & (* src = "cla/cla.sv:30.33-30.49" *) _285_;
  assign _137_ = _136_ | (* src = "cla/cla.sv:33.30-33.61" *) _302_;
  assign _140_ = _139_ | (* src = "cla/cla.sv:33.30-33.61" *) _303_;
  assign _141_ = _138_ | (* src = "cla/cla.sv:33.30-33.61" *) _304_;
  assign _143_ = _142_ | (* src = "cla/cla.sv:33.30-33.61" *) _305_;
  assign _145_ = _144_ | (* src = "cla/cla.sv:33.30-33.61" *) _306_;
  assign _147_ = _146_ | (* src = "cla/cla.sv:33.30-33.61" *) _307_;
  assign _149_ = _148_ | (* src = "cla/cla.sv:33.30-33.61" *) _308_;
  assign _151_ = _150_ | (* src = "cla/cla.sv:33.30-33.61" *) _309_;
  assign _153_ = _152_ | (* src = "cla/cla.sv:33.30-33.61" *) _310_;
  assign _155_ = _154_ | (* src = "cla/cla.sv:33.30-33.61" *) _311_;
  assign _157_ = _156_ | (* src = "cla/cla.sv:33.30-33.61" *) _312_;
  assign _159_ = _158_ | (* src = "cla/cla.sv:33.30-33.61" *) _313_;
  assign _161_ = _160_ | (* src = "cla/cla.sv:33.30-33.61" *) _314_;
  assign _163_ = _162_ | (* src = "cla/cla.sv:33.30-33.61" *) _315_;
  assign _165_ = _164_ | (* src = "cla/cla.sv:33.30-33.61" *) _316_;
  assign _167_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[8:1];
  assign _168_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[8:2];
  assign _169_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[8:3];
  assign _170_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[8:4];
  assign _171_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[8:5];
  assign _172_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[8:6];
  assign _173_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[8:7];
  assign _175_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[9:1];
  assign _176_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[9:2];
  assign _177_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[9:3];
  assign _178_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[9:4];
  assign _179_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[9:5];
  assign _180_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[9:6];
  assign _181_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[9:7];
  assign _182_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[9:8];
  assign _184_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[10:1];
  assign _185_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[10:2];
  assign _186_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[10:3];
  assign _187_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[10:4];
  assign _188_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[10:5];
  assign _189_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[10:6];
  assign _190_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[10:7];
  assign _191_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[10:8];
  assign _195_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[2:1];
  assign _192_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[10:9];
  assign _194_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[11:1];
  assign _196_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[11:2];
  assign _197_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[11:3];
  assign _198_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[11:4];
  assign _199_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[11:5];
  assign _200_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[11:6];
  assign _201_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[11:7];
  assign _202_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[11:8];
  assign _203_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[11:9];
  assign _204_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[11:10];
  assign _207_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:1];
  assign _208_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:2];
  assign _209_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:3];
  assign _210_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:4];
  assign _211_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:5];
  assign _212_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:6];
  assign _213_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:7];
  assign _214_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:8];
  assign _215_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:9];
  assign _216_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:10];
  assign _217_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[12:11];
  assign _219_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:1];
  assign _220_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:2];
  assign _221_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:3];
  assign _222_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:4];
  assign _223_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:5];
  assign _224_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:6];
  assign _225_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:7];
  assign _226_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:8];
  assign _227_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:9];
  assign _228_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:10];
  assign _229_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:11];
  assign _230_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[13:12];
  assign _234_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[3:1];
  assign _232_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:1];
  assign _233_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:2];
  assign _235_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:3];
  assign _236_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:4];
  assign _237_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:5];
  assign _238_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:6];
  assign _239_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:7];
  assign _245_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[3:2];
  assign _240_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:8];
  assign _241_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:9];
  assign _242_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:10];
  assign _243_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:11];
  assign _244_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:12];
  assign _246_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[14:13];
  assign _248_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:1];
  assign _249_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:2];
  assign _250_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:3];
  assign _251_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:4];
  assign _252_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:5];
  assign _253_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:6];
  assign _255_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:7];
  assign _256_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:8];
  assign _257_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:9];
  assign _258_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:10];
  assign _259_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:11];
  assign _260_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:12];
  assign _261_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:13];
  assign _262_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[15:14];
  assign _264_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[4:1];
  assign _265_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[4:2];
  assign _266_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[4:3];
  assign _268_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[5:1];
  assign _269_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[5:2];
  assign _270_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[5:3];
  assign _271_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[5:4];
  assign _273_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[6:1];
  assign _274_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[6:2];
  assign _275_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[6:3];
  assign _276_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[6:4];
  assign _277_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[6:5];
  assign _279_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[7:1];
  assign _280_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[7:2];
  assign _281_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[7:3];
  assign _282_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[7:4];
  assign _283_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[7:5];
  assign _284_ = & (* src = "cla/cla.sv:30.40-30.49" *) p[7:6];
  assign _288_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[1:0];
  assign _287_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[8:0];
  assign _289_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[9:0];
  assign _290_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[10:0];
  assign _291_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[11:0];
  assign _292_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[2:0];
  assign _293_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[12:0];
  assign _294_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[13:0];
  assign _295_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[14:0];
  assign _297_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[3:0];
  assign _296_ = & (* src = "cla/cla.sv:33.46-33.53" *) p;
  assign _298_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[4:0];
  assign _299_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[5:0];
  assign _300_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[6:0];
  assign _301_ = & (* src = "cla/cla.sv:33.46-33.53" *) p[7:0];
  assign _302_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[8].tmp ;
  assign _303_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[9].tmp ;
  assign _305_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[10].tmp ;
  assign _306_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[11].tmp ;
  assign _307_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[12].tmp ;
  assign _308_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[2].tmp ;
  assign _309_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[13].tmp ;
  assign _310_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[14].tmp ;
  assign _311_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[15].tmp ;
  assign _312_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[3].tmp ;
  assign _313_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[4].tmp ;
  assign _314_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[5].tmp ;
  assign _315_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[6].tmp ;
  assign _316_ = | (* src = "cla/cla.sv:33.57-33.61" *) \generate_carry_lookaheads[7].tmp ;
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[0].fa_i  (
    .a(a[0]),
    .b(b[0]),
    .ci(1'h0),
    .g(g[0]),
    .p(p[0]),
    .s(z[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[10].fa_i  (
    .a(a[10]),
    .b(b[10]),
    .ci(ci[10]),
    .g(g[10]),
    .p(p[10]),
    .s(z[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[11].fa_i  (
    .a(a[11]),
    .b(b[11]),
    .ci(ci[11]),
    .g(g[11]),
    .p(p[11]),
    .s(z[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[12].fa_i  (
    .a(a[12]),
    .b(b[12]),
    .ci(ci[12]),
    .g(g[12]),
    .p(p[12]),
    .s(z[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[13].fa_i  (
    .a(a[13]),
    .b(b[13]),
    .ci(ci[13]),
    .g(g[13]),
    .p(p[13]),
    .s(z[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[14].fa_i  (
    .a(a[14]),
    .b(b[14]),
    .ci(ci[14]),
    .g(g[14]),
    .p(p[14]),
    .s(z[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[15].fa_i  (
    .a(a[15]),
    .b(b[15]),
    .ci(ci[15]),
    .g(g[15]),
    .p(p[15]),
    .s(z[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[1].fa_i  (
    .a(a[1]),
    .b(b[1]),
    .ci(ci[1]),
    .g(g[1]),
    .p(p[1]),
    .s(z[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[2].fa_i  (
    .a(a[2]),
    .b(b[2]),
    .ci(ci[2]),
    .g(g[2]),
    .p(p[2]),
    .s(z[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[3].fa_i  (
    .a(a[3]),
    .b(b[3]),
    .ci(ci[3]),
    .g(g[3]),
    .p(p[3]),
    .s(z[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[4].fa_i  (
    .a(a[4]),
    .b(b[4]),
    .ci(ci[4]),
    .g(g[4]),
    .p(p[4]),
    .s(z[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[5].fa_i  (
    .a(a[5]),
    .b(b[5]),
    .ci(ci[5]),
    .g(g[5]),
    .p(p[5]),
    .s(z[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[6].fa_i  (
    .a(a[6]),
    .b(b[6]),
    .ci(ci[6]),
    .g(g[6]),
    .p(p[6]),
    .s(z[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[7].fa_i  (
    .a(a[7]),
    .b(b[7]),
    .ci(ci[7]),
    .g(g[7]),
    .p(p[7]),
    .s(z[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[8].fa_i  (
    .a(a[8]),
    .b(b[8]),
    .ci(ci[8]),
    .g(g[8]),
    .p(p[8]),
    .s(z[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "cla/cla.sv:15.28-22.14" *)
  cla_full_adder \generate_adder_modules[9].fa_i  (
    .a(a[9]),
    .b(b[9]),
    .ci(ci[9]),
    .g(g[9]),
    .p(p[9]),
    .s(z[9])
  );
  assign ci[0] = 1'h0;
  assign ci[1] = _166_;
  assign z[16] = ci[16];
  assign \generate_carry_lookaheads[1].tmp  = _005_;
  assign ci[2] = _141_;
  assign \generate_carry_lookaheads[2].tmp [0] = _033_;
  assign \generate_carry_lookaheads[2].tmp [1] = _042_;
  assign ci[3] = _149_;
  assign \generate_carry_lookaheads[3].tmp [0] = _073_;
  assign \generate_carry_lookaheads[3].tmp [1] = _081_;
  assign \generate_carry_lookaheads[3].tmp [2] = _092_;
  assign ci[4] = _157_;
  assign \generate_carry_lookaheads[4].tmp [0] = _098_;
  assign \generate_carry_lookaheads[4].tmp [1] = _099_;
  assign \generate_carry_lookaheads[4].tmp [2] = _100_;
  assign \generate_carry_lookaheads[4].tmp [3] = _101_;
  assign ci[5] = _159_;
  assign \generate_carry_lookaheads[5].tmp [0] = _102_;
  assign \generate_carry_lookaheads[5].tmp [1] = _103_;
  assign \generate_carry_lookaheads[5].tmp [2] = _104_;
  assign \generate_carry_lookaheads[5].tmp [3] = _105_;
  assign \generate_carry_lookaheads[5].tmp [4] = _106_;
  assign ci[6] = _161_;
  assign \generate_carry_lookaheads[6].tmp [0] = _107_;
  assign \generate_carry_lookaheads[6].tmp [1] = _108_;
  assign \generate_carry_lookaheads[6].tmp [2] = _109_;
  assign \generate_carry_lookaheads[6].tmp [3] = _110_;
  assign \generate_carry_lookaheads[6].tmp [4] = _111_;
  assign \generate_carry_lookaheads[6].tmp [5] = _112_;
  assign ci[7] = _163_;
  assign \generate_carry_lookaheads[7].tmp [0] = _113_;
  assign \generate_carry_lookaheads[7].tmp [1] = _114_;
  assign \generate_carry_lookaheads[7].tmp [2] = _115_;
  assign \generate_carry_lookaheads[7].tmp [3] = _116_;
  assign \generate_carry_lookaheads[7].tmp [4] = _117_;
  assign \generate_carry_lookaheads[7].tmp [5] = _118_;
  assign \generate_carry_lookaheads[7].tmp [6] = _119_;
  assign ci[8] = _165_;
  assign \generate_carry_lookaheads[8].tmp [0] = _000_;
  assign \generate_carry_lookaheads[8].tmp [1] = _001_;
  assign \generate_carry_lookaheads[8].tmp [2] = _002_;
  assign \generate_carry_lookaheads[8].tmp [3] = _003_;
  assign \generate_carry_lookaheads[8].tmp [4] = _004_;
  assign \generate_carry_lookaheads[8].tmp [5] = _006_;
  assign \generate_carry_lookaheads[8].tmp [6] = _007_;
  assign \generate_carry_lookaheads[8].tmp [7] = _008_;
  assign ci[9] = _137_;
  assign \generate_carry_lookaheads[9].tmp [0] = _009_;
  assign \generate_carry_lookaheads[9].tmp [1] = _010_;
  assign \generate_carry_lookaheads[9].tmp [2] = _011_;
  assign \generate_carry_lookaheads[9].tmp [3] = _012_;
  assign \generate_carry_lookaheads[9].tmp [4] = _013_;
  assign \generate_carry_lookaheads[9].tmp [5] = _014_;
  assign \generate_carry_lookaheads[9].tmp [6] = _015_;
  assign \generate_carry_lookaheads[9].tmp [7] = _016_;
  assign \generate_carry_lookaheads[9].tmp [8] = _017_;
  assign ci[10] = _140_;
  assign \generate_carry_lookaheads[10].tmp [0] = _018_;
  assign \generate_carry_lookaheads[10].tmp [1] = _019_;
  assign \generate_carry_lookaheads[10].tmp [2] = _020_;
  assign \generate_carry_lookaheads[10].tmp [3] = _021_;
  assign \generate_carry_lookaheads[10].tmp [4] = _022_;
  assign \generate_carry_lookaheads[10].tmp [5] = _023_;
  assign \generate_carry_lookaheads[10].tmp [6] = _024_;
  assign \generate_carry_lookaheads[10].tmp [7] = _025_;
  assign \generate_carry_lookaheads[10].tmp [8] = _026_;
  assign \generate_carry_lookaheads[10].tmp [9] = _027_;
  assign ci[11] = _143_;
  assign \generate_carry_lookaheads[11].tmp [0] = _028_;
  assign \generate_carry_lookaheads[11].tmp [1] = _029_;
  assign \generate_carry_lookaheads[11].tmp [2] = _030_;
  assign \generate_carry_lookaheads[11].tmp [3] = _031_;
  assign \generate_carry_lookaheads[11].tmp [4] = _032_;
  assign \generate_carry_lookaheads[11].tmp [5] = _034_;
  assign \generate_carry_lookaheads[11].tmp [6] = _035_;
  assign \generate_carry_lookaheads[11].tmp [7] = _036_;
  assign \generate_carry_lookaheads[11].tmp [8] = _037_;
  assign \generate_carry_lookaheads[11].tmp [9] = _038_;
  assign \generate_carry_lookaheads[11].tmp [10] = _039_;
  assign ci[12] = _145_;
  assign \generate_carry_lookaheads[12].tmp [0] = _040_;
  assign \generate_carry_lookaheads[12].tmp [1] = _041_;
  assign \generate_carry_lookaheads[12].tmp [2] = _043_;
  assign \generate_carry_lookaheads[12].tmp [3] = _044_;
  assign \generate_carry_lookaheads[12].tmp [4] = _045_;
  assign \generate_carry_lookaheads[12].tmp [5] = _046_;
  assign \generate_carry_lookaheads[12].tmp [6] = _047_;
  assign \generate_carry_lookaheads[12].tmp [7] = _048_;
  assign \generate_carry_lookaheads[12].tmp [8] = _049_;
  assign \generate_carry_lookaheads[12].tmp [9] = _050_;
  assign \generate_carry_lookaheads[12].tmp [10] = _051_;
  assign \generate_carry_lookaheads[12].tmp [11] = _052_;
  assign ci[13] = _147_;
  assign \generate_carry_lookaheads[13].tmp [0] = _053_;
  assign \generate_carry_lookaheads[13].tmp [1] = _054_;
  assign \generate_carry_lookaheads[13].tmp [2] = _055_;
  assign \generate_carry_lookaheads[13].tmp [3] = _056_;
  assign \generate_carry_lookaheads[13].tmp [4] = _057_;
  assign \generate_carry_lookaheads[13].tmp [5] = _058_;
  assign \generate_carry_lookaheads[13].tmp [6] = _059_;
  assign \generate_carry_lookaheads[13].tmp [7] = _060_;
  assign \generate_carry_lookaheads[13].tmp [8] = _061_;
  assign \generate_carry_lookaheads[13].tmp [9] = _062_;
  assign \generate_carry_lookaheads[13].tmp [10] = _063_;
  assign \generate_carry_lookaheads[13].tmp [11] = _064_;
  assign \generate_carry_lookaheads[13].tmp [12] = _065_;
  assign ci[14] = _151_;
  assign \generate_carry_lookaheads[14].tmp [0] = _066_;
  assign \generate_carry_lookaheads[14].tmp [1] = _067_;
  assign \generate_carry_lookaheads[14].tmp [2] = _068_;
  assign \generate_carry_lookaheads[14].tmp [3] = _069_;
  assign \generate_carry_lookaheads[14].tmp [4] = _070_;
  assign \generate_carry_lookaheads[14].tmp [5] = _071_;
  assign \generate_carry_lookaheads[14].tmp [6] = _072_;
  assign \generate_carry_lookaheads[14].tmp [7] = _074_;
  assign \generate_carry_lookaheads[14].tmp [8] = _075_;
  assign \generate_carry_lookaheads[14].tmp [9] = _076_;
  assign \generate_carry_lookaheads[14].tmp [10] = _077_;
  assign \generate_carry_lookaheads[14].tmp [11] = _078_;
  assign \generate_carry_lookaheads[14].tmp [12] = _079_;
  assign \generate_carry_lookaheads[14].tmp [13] = _080_;
  assign ci[15] = _153_;
  assign \generate_carry_lookaheads[15].tmp [0] = _082_;
  assign \generate_carry_lookaheads[15].tmp [1] = _083_;
  assign \generate_carry_lookaheads[15].tmp [2] = _084_;
  assign \generate_carry_lookaheads[15].tmp [3] = _085_;
  assign \generate_carry_lookaheads[15].tmp [4] = _086_;
  assign \generate_carry_lookaheads[15].tmp [5] = _087_;
  assign \generate_carry_lookaheads[15].tmp [6] = _088_;
  assign \generate_carry_lookaheads[15].tmp [7] = _089_;
  assign \generate_carry_lookaheads[15].tmp [8] = _090_;
  assign \generate_carry_lookaheads[15].tmp [9] = _091_;
  assign \generate_carry_lookaheads[15].tmp [10] = _093_;
  assign \generate_carry_lookaheads[15].tmp [11] = _094_;
  assign \generate_carry_lookaheads[15].tmp [12] = _095_;
  assign \generate_carry_lookaheads[15].tmp [13] = _096_;
  assign \generate_carry_lookaheads[15].tmp [14] = _097_;
  assign ci[16] = _155_;
  assign _135_ = 1'h0;
  assign _166_ = g[0];
  assign _286_ = p[1];
  assign _121_ = 1'h0;
  assign _138_ = g[1];
  assign _304_ = _005_;
  assign _206_ = p[2];
  assign _125_ = 1'h0;
  assign _148_ = g[2];
  assign _254_ = p[3];
  assign _130_ = 1'h0;
  assign _156_ = g[3];
  assign _267_ = p[4];
  assign _131_ = 1'h0;
  assign _158_ = g[4];
  assign _272_ = p[5];
  assign _132_ = 1'h0;
  assign _160_ = g[5];
  assign _278_ = p[6];
  assign _133_ = 1'h0;
  assign _162_ = g[6];
  assign _285_ = p[7];
  assign _134_ = 1'h0;
  assign _164_ = g[7];
  assign _174_ = p[8];
  assign _120_ = 1'h0;
  assign _136_ = g[8];
  assign _183_ = p[9];
  assign _122_ = 1'h0;
  assign _139_ = g[9];
  assign _193_ = p[10];
  assign _123_ = 1'h0;
  assign _142_ = g[10];
  assign _205_ = p[11];
  assign _124_ = 1'h0;
  assign _144_ = g[11];
  assign _218_ = p[12];
  assign _126_ = 1'h0;
  assign _146_ = g[12];
  assign _231_ = p[13];
  assign _127_ = 1'h0;
  assign _150_ = g[13];
  assign _247_ = p[14];
  assign _128_ = 1'h0;
  assign _152_ = g[14];
  assign _263_ = p[15];
  assign _129_ = 1'h0;
  assign _154_ = g[15];
endmodule

(* dynports =  1  *)
(* hdlname = "\\io_serdes" *)
(* src = "io_serdes/io_serdes.sv:1.1-71.10" *)
module \$paramod\io_serdes\WIDTH=s32'00000000000000000000000000010000 (clk, reset, inputs, outputs, a, b, z, start_calc, output_result);
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _000_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _001_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _002_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _003_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [31:0] _004_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [31:0] _005_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _006_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _007_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _008_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _009_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [5:0] _010_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [5:0] _011_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [7:0] _012_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [31:0] _013_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _014_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _015_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _016_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _017_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [31:0] _018_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [31:0] _019_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _020_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _021_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _022_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _023_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _024_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _025_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [31:0] _026_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [31:0] _027_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _028_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _029_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _030_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _031_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _032_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _033_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [31:0] _034_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [31:0] _035_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _036_;
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  wire [15:0] _037_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [31:0] _038_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [31:0] _039_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [31:0] _040_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _041_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _042_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _043_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _044_;
  (* nosync = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  reg [15:0] _045_;
  (* nosync = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  reg [15:0] _046_;
  (* nosync = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  reg [15:0] _047_;
  (* nosync = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  reg [15:0] _048_;
  (* nosync = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  reg [31:0] _049_;
  (* nosync = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  reg [31:0] _050_;
  (* src = "io_serdes/io_serdes.sv:24.13-24.26" *)
  wire _051_;
  (* src = "io_serdes/io_serdes.sv:68.16-68.40" *)
  wire [31:0] _052_;
  (* src = "io_serdes/io_serdes.sv:69.16-69.40" *)
  wire [31:0] _053_;
  (* src = "io_serdes/io_serdes.sv:36.17-36.34" *)
  wire _054_;
  (* src = "io_serdes/io_serdes.sv:48.25-48.41" *)
  wire _055_;
  (* src = "io_serdes/io_serdes.sv:58.25-58.41" *)
  wire _056_;
  (* nosync = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  reg [15:0] _057_;
  (* nosync = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  reg [15:0] _058_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [32:0] _059_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [32:0] _060_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [32:0] _061_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [32:0] _062_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _063_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _064_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _065_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _066_;
  wire [15:0] _067_;
  wire _068_;
  wire [15:0] _069_;
  wire _070_;
  wire [15:0] _071_;
  wire _072_;
  wire [15:0] _073_;
  wire _074_;
  wire [15:0] _075_;
  wire _076_;
  wire [15:0] _077_;
  wire _078_;
  wire [15:0] _079_;
  wire _080_;
  wire [15:0] _081_;
  wire _082_;
  wire [15:0] _083_;
  wire _084_;
  wire [31:0] _085_;
  wire _086_;
  wire [31:0] _087_;
  wire _088_;
  wire [31:0] _089_;
  wire _090_;
  wire [15:0] _091_;
  wire _092_;
  wire [15:0] _093_;
  wire _094_;
  wire [15:0] _095_;
  wire _096_;
  wire [31:0] _097_;
  wire _098_;
  wire [31:0] _099_;
  wire _100_;
  wire [31:0] _101_;
  wire _102_;
  wire [15:0] _103_;
  wire _104_;
  wire [15:0] _105_;
  wire _106_;
  wire [15:0] _107_;
  wire _108_;
  wire [15:0] _109_;
  wire _110_;
  wire [15:0] _111_;
  wire _112_;
  wire [15:0] _113_;
  wire _114_;
  wire [15:0] _115_;
  wire _116_;
  wire [15:0] _117_;
  wire _118_;
  wire [15:0] _119_;
  wire _120_;
  wire [15:0] _121_;
  wire _122_;
  wire [31:0] _123_;
  wire _124_;
  wire [31:0] _125_;
  wire _126_;
  wire [15:0] _127_;
  wire _128_;
  wire [15:0] _129_;
  wire _130_;
  wire [15:0] _131_;
  wire _132_;
  wire [15:0] _133_;
  wire _134_;
  wire [31:0] _135_;
  wire _136_;
  wire [31:0] _137_;
  wire _138_;
  wire [15:0] _139_;
  wire _140_;
  wire [15:0] _141_;
  wire _142_;
  wire [15:0] _143_;
  wire _144_;
  wire [15:0] _145_;
  wire _146_;
  wire [15:0] _147_;
  wire _148_;
  wire [15:0] _149_;
  wire _150_;
  wire [31:0] _151_;
  wire _152_;
  wire [15:0] _153_;
  wire _154_;
  wire [15:0] _155_;
  wire _156_;
  wire [31:0] _157_;
  wire _158_;
  wire [15:0] _159_;
  wire _160_;
  wire [15:0] _161_;
  wire _162_;
  wire [31:0] _163_;
  wire _164_;
  wire [31:0] _165_;
  wire _166_;
  wire [31:0] _167_;
  wire _168_;
  wire _169_;
  wire [31:0] _170_;
  wire _171_;
  wire [31:0] _172_;
  wire _173_;
  wire [31:0] _174_;
  wire _175_;
  wire [5:0] _176_;
  wire _177_;
  wire [5:0] _178_;
  wire _179_;
  wire [5:0] _180_;
  wire _181_;
  wire [5:0] _182_;
  wire _183_;
  wire [5:0] _184_;
  wire _185_;
  wire [5:0] _186_;
  wire _187_;
  wire _188_;
  wire [5:0] _189_;
  wire _190_;
  wire [5:0] _191_;
  wire _192_;
  wire [7:0] _193_;
  wire _194_;
  wire [7:0] _195_;
  wire _196_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _197_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _198_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _199_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [15:0] _200_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [7:0] _201_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [31:0] _202_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [31:0] _203_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [32:0] _204_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [32:0] _205_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [31:0] _206_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [32:0] _207_;
  (* src = "io_serdes/io_serdes.sv:0.0-0.0" *)
  wire [32:0] _208_;
  (* src = "io_serdes/io_serdes.sv:40.33-40.49" *)
  wire [31:0] _209_;
  (* src = "io_serdes/io_serdes.sv:52.38-52.53" *)
  wire [31:0] _210_;
  (* src = "io_serdes/io_serdes.sv:62.38-62.53" *)
  wire [31:0] _211_;
  (* src = "io_serdes/io_serdes.sv:68.16-68.40" *)
  wire [31:0] _212_;
  (* src = "io_serdes/io_serdes.sv:69.16-69.40" *)
  wire [31:0] _213_;
  (* src = "io_serdes/io_serdes.sv:8.30-8.31" *)
  output [15:0] a;
  wire [15:0] a;
  (* src = "io_serdes/io_serdes.sv:16.30-16.35" *)
  reg [15:0] a_reg;
  (* src = "io_serdes/io_serdes.sv:9.30-9.31" *)
  output [15:0] b;
  wire [15:0] b;
  (* src = "io_serdes/io_serdes.sv:16.37-16.42" *)
  reg [15:0] b_reg;
  (* src = "io_serdes/io_serdes.sv:2.30-2.33" *)
  input clk;
  wire clk;
  (* src = "io_serdes/io_serdes.sv:17.30-17.41" *)
  reg [5:0] input_index;
  (* src = "io_serdes/io_serdes.sv:5.30-5.36" *)
  input [7:0] inputs;
  wire [7:0] inputs;
  (* src = "io_serdes/io_serdes.sv:18.30-18.42" *)
  reg [5:0] output_index;
  (* src = "io_serdes/io_serdes.sv:13.30-13.43" *)
  input output_result;
  wire output_result;
  (* src = "io_serdes/io_serdes.sv:6.30-6.37" *)
  output [7:0] outputs;
  reg [7:0] outputs;
  (* src = "io_serdes/io_serdes.sv:3.30-3.35" *)
  input reset;
  wire reset;
  (* src = "io_serdes/io_serdes.sv:12.30-12.40" *)
  input start_calc;
  wire start_calc;
  (* enum_value_00000000000000000000000000000000 = "\\IDLE" *)
  (* enum_value_00000000000000000000000000000001 = "\\READ_A" *)
  (* enum_value_00000000000000000000000000000010 = "\\READ_B" *)
  (* src = "io_serdes/io_serdes.sv:21.14-21.19" *)
  (* wiretype = "\\states_t" *)
  reg [31:0] state;
  (* src = "io_serdes/io_serdes.sv:10.30-10.31" *)
  input [15:0] z;
  wire [15:0] z;
  assign _038_ = { 26'h0000000, output_index } + (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) 32'd1;
  assign _039_ = { 26'h0000000, input_index } + (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) 32'd1;
  assign _040_ = { 26'h0000000, input_index } + (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) 32'd1;
  assign _042_ = a_reg & (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) _063_;
  assign _044_ = b_reg & (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) _064_;
  assign _051_ = ~ (* src = "io_serdes/io_serdes.sv:24.13-24.26" *) reset;
  assign _052_ = + (* src = "io_serdes/io_serdes.sv:68.16-68.40" *) a_reg;
  assign _053_ = + (* src = "io_serdes/io_serdes.sv:69.16-69.40" *) b_reg;
  assign _054_ = output_index <= (* src = "io_serdes/io_serdes.sv:36.17-36.34" *) 32'd7;
  assign _055_ = input_index <= (* src = "io_serdes/io_serdes.sv:48.25-48.41" *) 32'd7;
  assign _056_ = input_index <= (* src = "io_serdes/io_serdes.sv:58.25-58.41" *) 32'd7;
  assign _059_ = - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) $signed(_204_);
  assign _060_ = - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) $signed(_205_);
  assign _061_ = - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) $signed(_207_);
  assign _062_ = - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) $signed(_208_);
  assign _063_ = ~ (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) _197_;
  assign _064_ = ~ (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) _199_;
  assign _065_ = _042_ | (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) _198_;
  assign _066_ = _044_ | (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) _200_;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    outputs <= _195_;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    a_reg <= _149_;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    b_reg <= _147_;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    input_index <= _191_;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    output_index <= _180_;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    state <= _174_;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    _047_ <= 16'hxxxx;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    _045_ <= 16'hxxxx;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    _049_ <= 32'hxxxxxxxx;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    _048_ <= 16'hxxxx;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    _046_ <= 16'hxxxx;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    _050_ <= 32'hxxxxxxxx;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    _057_ <= 16'hxxxx;
  (* \always_ff  = 32'd1 *)
  (* src = "io_serdes/io_serdes.sv:23.5-66.8" *)
  always @(posedge clk)
    _058_ <= 16'hxxxx;
  assign _067_ = _068_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) _065_ : a_reg;
  assign _068_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd1;
  assign _069_ = _070_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) 16'hxxxx : _067_;
  assign _071_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _069_ : 16'hxxxx;
  assign _073_ = _074_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) _198_ : _045_;
  assign _074_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd1;
  assign _075_ = _076_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) 16'hxxxx : _073_;
  assign _077_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _075_ : 16'hxxxx;
  assign _079_ = _080_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) _197_ : _047_;
  assign _080_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd1;
  assign _081_ = _082_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) 16'hxxxx : _079_;
  assign _083_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _081_ : 16'hxxxx;
  assign _085_ = _086_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) _203_ : _049_;
  assign _086_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd1;
  assign _087_ = _088_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) 32'hxxxxxxxx : _085_;
  assign _089_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _087_ : 32'hxxxxxxxx;
  assign _091_ = _092_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) _066_ : b_reg;
  assign _092_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd2;
  assign _093_ = _094_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) 16'hxxxx : _091_;
  assign _095_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _093_ : 16'hxxxx;
  assign _097_ = _098_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) _206_ : _050_;
  assign _098_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd2;
  assign _099_ = _100_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) 32'hxxxxxxxx : _097_;
  assign _101_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _099_ : 32'hxxxxxxxx;
  assign _103_ = _104_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) _200_ : _046_;
  assign _104_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd2;
  assign _105_ = _106_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) 16'hxxxx : _103_;
  assign _107_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _105_ : 16'hxxxx;
  assign _109_ = _110_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) _199_ : _048_;
  assign _110_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd2;
  assign _111_ = _112_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) 16'hxxxx : _109_;
  assign _113_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _111_ : 16'hxxxx;
  assign _115_ = _116_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) b_reg : _037_;
  assign _117_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _115_ : 16'hxxxx;
  assign _119_ = _120_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) a_reg : _036_;
  assign _121_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _119_ : 16'hxxxx;
  assign _123_ = _124_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) _050_ : _035_;
  assign _125_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _123_ : 32'hxxxxxxxx;
  assign _127_ = _128_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) _046_ : _031_;
  assign _129_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _127_ : 16'hxxxx;
  assign _131_ = _132_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) _048_ : _033_;
  assign _133_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _131_ : 16'hxxxx;
  assign _135_ = _136_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) _049_ : _034_;
  assign _137_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _135_ : 32'hxxxxxxxx;
  assign _139_ = _140_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) _045_ : _030_;
  assign _141_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _139_ : 16'hxxxx;
  assign _143_ = _144_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) _047_ : _032_;
  assign _145_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _143_ : 16'hxxxx;
  assign _147_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _029_ : 16'h0000;
  assign _149_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _028_ : 16'h0000;
  assign _151_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _027_ : _050_;
  assign _153_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _023_ : _046_;
  assign _155_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _025_ : _048_;
  assign _157_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _026_ : _049_;
  assign _159_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _022_ : _045_;
  assign _161_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _024_ : _047_;
  assign _163_ = _164_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:58.25-58.41|io_serdes/io_serdes.sv:58.21-62.54" *) 32'd0 : state;
  function [31:0] _304_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _304_ = b[31:0];
      2'b1?:
        _304_ = b[63:32];
      default:
        _304_ = a;
    endcase
  endfunction
  assign _165_ = _304_(state, { _167_, _163_ }, { _169_, _166_ });
  assign _166_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd2;
  assign _167_ = _168_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:48.25-48.41|io_serdes/io_serdes.sv:48.21-52.54" *) 32'd2 : state;
  assign _169_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd1;
  assign _170_ = _171_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:36.17-36.34|io_serdes/io_serdes.sv:36.13-40.50" *) 32'd0 : state;
  assign _172_ = _173_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) _170_ : _165_;
  assign _174_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _172_ : 32'd1;
  assign _176_ = _177_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:36.17-36.34|io_serdes/io_serdes.sv:36.13-40.50" *) 6'h0f : _209_[5:0];
  assign _178_ = _179_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) _176_ : output_index;
  assign _180_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _178_ : 6'h0f;
  assign _182_ = _183_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:58.25-58.41|io_serdes/io_serdes.sv:58.21-62.54" *) 6'h0f : _211_[5:0];
  function [5:0] _315_;
    input [5:0] a;
    input [11:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _315_ = b[5:0];
      2'b1?:
        _315_ = b[11:6];
      default:
        _315_ = a;
    endcase
  endfunction
  assign _184_ = _315_(input_index, { _186_, _182_ }, { _188_, _185_ });
  assign _185_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd2;
  assign _186_ = _187_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:48.25-48.41|io_serdes/io_serdes.sv:48.21-52.54" *) 6'h0f : _210_[5:0];
  assign _188_ = state == (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:0.0-0.0|io_serdes/io_serdes.sv:44.13-64.20" *) 32'd1;
  assign _189_ = _190_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) input_index : _184_;
  assign _191_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _189_ : 6'h0f;
  assign _193_ = _194_ ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:33.18-33.31|io_serdes/io_serdes.sv:33.14-65.12" *) _201_ : outputs;
  assign _195_ = reset ? (* full_case = 32'd1 *) (* src = "io_serdes/io_serdes.sv:24.13-24.26|io_serdes/io_serdes.sv:24.9-65.12" *) _193_ : 8'h00;
  assign _197_ = $signed(_059_) < 0 ? 8'hff << - _059_ : 8'hff >> _059_;
  assign _198_ = $signed(_060_) < 0 ? inputs << - _060_ : inputs >> _060_;
  assign _199_ = $signed(_061_) < 0 ? 8'hff << - _061_ : 8'hff >> _061_;
  assign _200_ = $signed(_062_) < 0 ? inputs << - _062_ : inputs >> _062_;
  wire [15:0] _340_ = z;
  assign _201_ = _340_[$signed(_202_) +: 8];
  assign _202_ = _038_ - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) 32'd8;
  assign _203_ = _039_ - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) 32'd8;
  assign _204_ = $signed({ 1'h0, _203_ }) - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) $signed(32'd0);
  assign _205_ = $signed({ 1'h0, _203_ }) - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) $signed(32'd0);
  assign _206_ = _040_ - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) 32'd8;
  assign _207_ = $signed({ 1'h0, _206_ }) - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) $signed(32'd0);
  assign _208_ = $signed({ 1'h0, _206_ }) - (* src = "io_serdes/io_serdes.sv:0.0-0.0" *) $signed(32'd0);
  assign _209_ = output_index - (* src = "io_serdes/io_serdes.sv:40.33-40.49" *) 32'd8;
  assign _210_ = input_index - (* src = "io_serdes/io_serdes.sv:52.38-52.53" *) 32'd8;
  assign _211_ = input_index - (* src = "io_serdes/io_serdes.sv:62.38-62.53" *) 32'd8;
  assign _212_ = start_calc ? (* src = "io_serdes/io_serdes.sv:68.16-68.40" *) _052_ : 32'd0;
  assign _213_ = start_calc ? (* src = "io_serdes/io_serdes.sv:69.16-69.40" *) _053_ : 32'd0;
  assign a = _212_[15:0];
  assign b = _213_[15:0];
  assign _008_ = _020_;
  assign _009_ = _021_;
  assign _007_ = _021_;
  assign _006_ = _020_;
  assign _005_ = _019_;
  assign _001_ = _015_;
  assign _003_ = _017_;
  assign _004_ = _018_;
  assign _000_ = _014_;
  assign _002_ = _016_;
  assign _070_ = output_result;
  assign _072_ = _051_;
  assign _036_ = _071_;
  assign _076_ = output_result;
  assign _078_ = _051_;
  assign _030_ = _077_;
  assign _082_ = output_result;
  assign _084_ = _051_;
  assign _032_ = _083_;
  assign _088_ = output_result;
  assign _090_ = _051_;
  assign _034_ = _089_;
  assign _094_ = output_result;
  assign _096_ = _051_;
  assign _037_ = _095_;
  assign _100_ = output_result;
  assign _102_ = _051_;
  assign _035_ = _101_;
  assign _106_ = output_result;
  assign _108_ = _051_;
  assign _031_ = _107_;
  assign _112_ = output_result;
  assign _114_ = _051_;
  assign _033_ = _113_;
  assign _116_ = output_result;
  assign _118_ = _051_;
  assign _029_ = _117_;
  assign _120_ = output_result;
  assign _122_ = _051_;
  assign _028_ = _121_;
  assign _124_ = output_result;
  assign _126_ = _051_;
  assign _027_ = _125_;
  assign _128_ = output_result;
  assign _130_ = _051_;
  assign _023_ = _129_;
  assign _132_ = output_result;
  assign _134_ = _051_;
  assign _025_ = _133_;
  assign _136_ = output_result;
  assign _138_ = _051_;
  assign _026_ = _137_;
  assign _140_ = output_result;
  assign _142_ = _051_;
  assign _022_ = _141_;
  assign _144_ = output_result;
  assign _146_ = _051_;
  assign _024_ = _145_;
  assign _148_ = _051_;
  assign _021_ = _147_;
  assign _150_ = _051_;
  assign _020_ = _149_;
  assign _152_ = _051_;
  assign _019_ = _151_;
  assign _154_ = _051_;
  assign _015_ = _153_;
  assign _156_ = _051_;
  assign _017_ = _155_;
  assign _158_ = _051_;
  assign _018_ = _157_;
  assign _160_ = _051_;
  assign _014_ = _159_;
  assign _162_ = _051_;
  assign _016_ = _161_;
  assign _164_ = _056_;
  assign _168_ = _055_;
  assign _171_ = _054_;
  assign _173_ = output_result;
  assign _175_ = _051_;
  assign _013_ = _174_;
  assign _177_ = _054_;
  assign _179_ = output_result;
  assign _181_ = _051_;
  assign _011_ = _180_;
  assign _183_ = _056_;
  assign _187_ = _055_;
  assign _190_ = output_result;
  assign _192_ = _051_;
  assign _010_ = _191_;
  assign _194_ = output_result;
  assign _196_ = _051_;
  assign _012_ = _195_;
  assign _041_[15:8] = 8'h00;
  assign _041_[7:0] = inputs;
  assign _043_[15:8] = 8'h00;
  assign _043_[7:0] = inputs;
endmodule

(* dynports =  1  *)
(* hdlname = "\\rca" *)
(* src = "rca/rca.sv:1.1-33.10" *)
module \$paramod\rca\WIDTH=s32'00000000000000000000000000010000 (a, b, c_in, s);
  (* src = "rca/rca.sv:2.29-2.30" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "rca/rca.sv:3.29-3.30" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "rca/rca.sv:4.29-4.33" *)
  input [15:0] c_in;
  wire [15:0] c_in;
  (* src = "rca/rca.sv:8.21-8.29" *)
  wire [16:0] cc_carry;
  (* src = "rca/rca.sv:5.29-5.30" *)
  output [16:0] s;
  wire [16:0] s;
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[0].fa  (
    .a(a[0]),
    .b(b[0]),
    .c_in(1'h0),
    .c_out(cc_carry[1]),
    .s(s[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[10].fa  (
    .a(a[10]),
    .b(b[10]),
    .c_in(cc_carry[10]),
    .c_out(cc_carry[11]),
    .s(s[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[11].fa  (
    .a(a[11]),
    .b(b[11]),
    .c_in(cc_carry[11]),
    .c_out(cc_carry[12]),
    .s(s[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[12].fa  (
    .a(a[12]),
    .b(b[12]),
    .c_in(cc_carry[12]),
    .c_out(cc_carry[13]),
    .s(s[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[13].fa  (
    .a(a[13]),
    .b(b[13]),
    .c_in(cc_carry[13]),
    .c_out(cc_carry[14]),
    .s(s[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[14].fa  (
    .a(a[14]),
    .b(b[14]),
    .c_in(cc_carry[14]),
    .c_out(cc_carry[15]),
    .s(s[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[15].fa  (
    .a(a[15]),
    .b(b[15]),
    .c_in(cc_carry[15]),
    .c_out(cc_carry[16]),
    .s(s[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[1].fa  (
    .a(a[1]),
    .b(b[1]),
    .c_in(cc_carry[1]),
    .c_out(cc_carry[2]),
    .s(s[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[2].fa  (
    .a(a[2]),
    .b(b[2]),
    .c_in(cc_carry[2]),
    .c_out(cc_carry[3]),
    .s(s[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[3].fa  (
    .a(a[3]),
    .b(b[3]),
    .c_in(cc_carry[3]),
    .c_out(cc_carry[4]),
    .s(s[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[4].fa  (
    .a(a[4]),
    .b(b[4]),
    .c_in(cc_carry[4]),
    .c_out(cc_carry[5]),
    .s(s[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[5].fa  (
    .a(a[5]),
    .b(b[5]),
    .c_in(cc_carry[5]),
    .c_out(cc_carry[6]),
    .s(s[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[6].fa  (
    .a(a[6]),
    .b(b[6]),
    .c_in(cc_carry[6]),
    .c_out(cc_carry[7]),
    .s(s[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[7].fa  (
    .a(a[7]),
    .b(b[7]),
    .c_in(cc_carry[7]),
    .c_out(cc_carry[8]),
    .s(s[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[8].fa  (
    .a(a[8]),
    .b(b[8]),
    .c_in(cc_carry[8]),
    .c_out(cc_carry[9]),
    .s(s[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca/rca.sv:15.27-21.14" *)
  rca_fulladder \generate_adder_modules[9].fa  (
    .a(a[9]),
    .b(b[9]),
    .c_in(cc_carry[9]),
    .c_out(cc_carry[10]),
    .s(s[9])
  );
  assign cc_carry[0] = 1'h0;
  assign s[16] = cc_carry[16];
endmodule

(* hdlname = "\\baverage" *)
(* src = "baverage/baverage.sv:1.1-43.10" *)
module baverage(x, clk, rst, y);
  (* src = "baverage/baverage.sv:0.0-0.0" *)
  wire [31:0] _00_;
  (* src = "baverage/baverage.sv:12.5-17.8" *)
  wire [31:0] _01_;
  (* src = "baverage/baverage.sv:0.0-0.0" *)
  wire _02_;
  (* src = "baverage/baverage.sv:0.0-0.0" *)
  wire [31:0] _03_;
  (* src = "baverage/baverage.sv:0.0-0.0" *)
  wire _04_;
  (* src = "baverage/baverage.sv:0.0-0.0" *)
  wire [31:0] _05_;
  (* src = "baverage/baverage.sv:0.0-0.0" *)
  wire [31:0] _06_;
  (* src = "baverage/baverage.sv:0.0-0.0" *)
  wire [31:0] _07_;
  (* src = "baverage/baverage.sv:21.12-21.27" *)
  wire _08_;
  (* src = "baverage/baverage.sv:27.12-27.22" *)
  wire _09_;
  (* src = "baverage/baverage.sv:34.21-34.31" *)
  wire _10_;
  wire [31:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [31:0] _15_;
  wire _16_;
  wire [31:0] _17_;
  wire _18_;
  wire [31:0] _19_;
  wire _20_;
  wire [31:0] _21_;
  wire _22_;
  wire [31:0] _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [31:0] _27_;
  wire _28_;
  wire [31:0] _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire [31:0] _33_;
  wire _34_;
  (* src = "baverage/baverage.sv:3.21-3.24" *)
  input clk;
  wire clk;
  (* src = "baverage/baverage.sv:4.21-4.24" *)
  input rst;
  wire rst;
  (* enum_value_00000000000000000000000000000000 = "\\z0" *)
  (* enum_value_00000000000000000000000000000001 = "\\z50" *)
  (* enum_value_00000000000000000000000000000010 = "\\z100" *)
  (* enum_value_00000000000000000000000000000011 = "\\z150" *)
  (* src = "baverage/baverage.sv:9.13-9.20" *)
  (* wiretype = "\\mystate" *)
  wire [31:0] state_d;
  (* enum_value_00000000000000000000000000000000 = "\\z0" *)
  (* enum_value_00000000000000000000000000000001 = "\\z50" *)
  (* enum_value_00000000000000000000000000000010 = "\\z100" *)
  (* enum_value_00000000000000000000000000000011 = "\\z150" *)
  (* src = "baverage/baverage.sv:10.13-10.20" *)
  (* wiretype = "\\mystate" *)
  reg [31:0] state_q;
  (* src = "baverage/baverage.sv:2.27-2.28" *)
  input [1:0] x;
  wire [1:0] x;
  (* src = "baverage/baverage.sv:5.22-5.23" *)
  output y;
  wire y;
  assign _08_ = state_q == (* src = "baverage/baverage.sv:21.12-21.27" *) 32'd3;
  assign _09_ = x == (* src = "baverage/baverage.sv:27.12-27.22" *) 2'h1;
  assign _10_ = x == (* src = "baverage/baverage.sv:34.21-34.31" *) 2'h2;
  (* \always_ff  = 32'd1 *)
  (* src = "baverage/baverage.sv:12.5-17.8" *)
  always @(posedge clk)
    state_q <= _33_;
  function [31:0] _39_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "baverage/baverage.sv:0.0-0.0|baverage/baverage.sv:35.13-40.20" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _39_ = b[31:0];
      3'b?1?:
        _39_ = b[63:32];
      3'b1??:
        _39_ = b[95:64];
      default:
        _39_ = a;
    endcase
  endfunction
  assign _11_ = _39_(state_q, 96'h000000020000000300000003, { _14_, _13_, _12_ });
  assign _12_ = state_q == (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:0.0-0.0|baverage/baverage.sv:35.13-40.20" *) 32'd2;
  assign _13_ = state_q == (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:0.0-0.0|baverage/baverage.sv:35.13-40.20" *) 32'd1;
  assign _14_ = ! (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:0.0-0.0|baverage/baverage.sv:35.13-40.20" *) state_q;
  assign _15_ = _16_ ? (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:34.21-34.31|baverage/baverage.sv:34.18-41.12" *) _11_ : 32'hxxxxxxxx;
  assign _17_ = _18_ ? (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:27.12-27.22|baverage/baverage.sv:27.9-41.12" *) 32'hxxxxxxxx : _15_;
  assign _19_ = _20_ ? (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:34.21-34.31|baverage/baverage.sv:34.18-41.12" *) _07_ : state_q;
  assign _21_ = _22_ ? (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:27.12-27.22|baverage/baverage.sv:27.9-41.12" *) 32'hxxxxxxxx : _19_;
  function [31:0] _47_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "baverage/baverage.sv:0.0-0.0|baverage/baverage.sv:28.13-33.20" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _47_ = b[31:0];
      3'b?1?:
        _47_ = b[63:32];
      3'b1??:
        _47_ = b[95:64];
      default:
        _47_ = a;
    endcase
  endfunction
  assign _23_ = _47_(state_q, 96'h000000010000000200000003, { _26_, _25_, _24_ });
  assign _24_ = state_q == (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:0.0-0.0|baverage/baverage.sv:28.13-33.20" *) 32'd2;
  assign _25_ = state_q == (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:0.0-0.0|baverage/baverage.sv:28.13-33.20" *) 32'd1;
  assign _26_ = ! (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:0.0-0.0|baverage/baverage.sv:28.13-33.20" *) state_q;
  assign _27_ = _28_ ? (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:27.12-27.22|baverage/baverage.sv:27.9-41.12" *) _23_ : 32'hxxxxxxxx;
  assign _29_ = _30_ ? (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:27.12-27.22|baverage/baverage.sv:27.9-41.12" *) _05_ : _06_;
  assign _31_ = _32_ ? (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:21.12-21.27|baverage/baverage.sv:21.9-22.19" *) 1'h1 : 1'h0;
  assign _33_ = _34_ ? (* full_case = 32'd1 *) (* src = "baverage/baverage.sv:13.13-13.16|baverage/baverage.sv:13.9-16.32" *) 32'd0 : state_d;
  assign _00_ = _03_;
  assign _02_ = _04_;
  assign _16_ = _10_;
  assign _18_ = _09_;
  assign _07_ = _17_;
  assign _20_ = _10_;
  assign _22_ = _09_;
  assign _06_ = _21_;
  assign _28_ = _09_;
  assign _05_ = _27_;
  assign _30_ = _09_;
  assign _03_ = _29_;
  assign _32_ = _08_;
  assign _04_ = _31_;
  assign _34_ = rst;
  assign _01_ = _33_;
  assign state_d = _29_;
  assign y = _31_;
endmodule

(* hdlname = "\\cla_full_adder" *)
(* src = "cla/cla_full_adder.sv:1.1-15.10" *)
module cla_full_adder(a, b, ci, s, p, g);
  (* src = "cla/cla_full_adder.sv:11.16-11.21" *)
  wire _0_;
  (* src = "cla/cla_full_adder.sv:12.16-12.21" *)
  wire _1_;
  (* src = "cla/cla_full_adder.sv:13.16-13.21" *)
  wire _2_;
  (* src = "cla/cla_full_adder.sv:13.16-13.26" *)
  wire _3_;
  (* src = "cla/cla_full_adder.sv:2.17-2.18" *)
  input a;
  wire a;
  (* src = "cla/cla_full_adder.sv:3.17-3.18" *)
  input b;
  wire b;
  (* src = "cla/cla_full_adder.sv:4.17-4.19" *)
  input ci;
  wire ci;
  (* src = "cla/cla_full_adder.sv:8.18-8.19" *)
  output g;
  wire g;
  (* src = "cla/cla_full_adder.sv:7.18-7.19" *)
  output p;
  wire p;
  (* src = "cla/cla_full_adder.sv:6.18-6.19" *)
  output s;
  wire s;
  assign _0_ = a & (* src = "cla/cla_full_adder.sv:11.16-11.21" *) b;
  assign _1_ = a ^ (* src = "cla/cla_full_adder.sv:12.16-12.21" *) b;
  assign _2_ = a ^ (* src = "cla/cla_full_adder.sv:13.16-13.21" *) b;
  assign _3_ = _2_ ^ (* src = "cla/cla_full_adder.sv:13.16-13.26" *) ci;
  assign g = _0_;
  assign p = _1_;
  assign s = _3_;
endmodule

(* hdlname = "\\rca_fulladder" *)
(* src = "rca/rca_fulladder.sv:1.1-13.10" *)
module rca_fulladder(a, b, c_in, s, c_out);
  (* src = "rca/rca_fulladder.sv:11.21-11.26" *)
  wire _00_;
  (* src = "rca/rca_fulladder.sv:11.31-11.45" *)
  wire _01_;
  (* src = "rca/rca_fulladder.sv:11.20-11.46" *)
  wire _02_;
  (* src = "rca/rca_fulladder.sv:10.16-10.21" *)
  wire _03_;
  (* src = "rca/rca_fulladder.sv:10.16-10.28" *)
  wire _04_;
  (* src = "rca/rca_fulladder.sv:11.39-11.44" *)
  wire _05_;
  (* src = "rca/rca_fulladder.sv:2.17-2.18" *)
  input a;
  wire a;
  (* src = "rca/rca_fulladder.sv:3.17-3.18" *)
  input b;
  wire b;
  (* src = "rca/rca_fulladder.sv:4.17-4.21" *)
  input c_in;
  wire c_in;
  (* src = "rca/rca_fulladder.sv:7.18-7.23" *)
  output c_out;
  wire c_out;
  (* src = "rca/rca_fulladder.sv:6.18-6.19" *)
  output s;
  wire s;
  assign _00_ = a & (* src = "rca/rca_fulladder.sv:11.21-11.26" *) b;
  assign _01_ = c_in & (* src = "rca/rca_fulladder.sv:11.31-11.45" *) _05_;
  assign _02_ = _00_ | (* src = "rca/rca_fulladder.sv:11.20-11.46" *) _01_;
  assign _03_ = a ^ (* src = "rca/rca_fulladder.sv:10.16-10.21" *) b;
  assign _04_ = _03_ ^ (* src = "rca/rca_fulladder.sv:10.16-10.28" *) c_in;
  assign _05_ = a ^ (* src = "rca/rca_fulladder.sv:11.39-11.44" *) b;
  assign s = _04_;
  assign c_out = _02_;
endmodule

(* hdlname = "\\tt_um_cejmu" *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "tt_um_cejmu.sv:8.1-89.10" *)
module tt_um_cejmu(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  (* src = "tt_um_cejmu.sv:54.11-54.45" *)
  wire _00_;
  (* src = "tt_um_cejmu.sv:0.0-0.0" *)
  wire [7:0] _01_;
  (* src = "tt_um_cejmu.sv:0.0-0.0" *)
  wire [7:0] _02_;
  (* src = "tt_um_cejmu.sv:75.26-75.46" *)
  wire _03_;
  (* src = "tt_um_cejmu.sv:51.18-51.24" *)
  wire _04_;
  wire [7:0] _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "tt_um_cejmu.sv:54.21-54.45" *)
  wire _09_;
  (* src = "tt_um_cejmu.sv:75.25-75.63" *)
  wire [16:0] _10_;
  (* src = "tt_um_cejmu.sv:54.11-54.18" *)
  wire _unused;
  (* src = "tt_um_cejmu.sv:26.24-26.29" *)
  wire [15:0] add_a;
  (* src = "tt_um_cejmu.sv:26.31-26.36" *)
  wire [15:0] add_b;
  (* src = "tt_um_cejmu.sv:27.38-27.48" *)
  wire [16:0] add_result;
  (* src = "tt_um_cejmu.sv:23.24-23.32" *)
  wire bav0_out;
  (* src = "tt_um_cejmu.sv:27.24-27.29" *)
  wire [16:0] cla_z;
  (* src = "tt_um_cejmu.sv:15.24-15.27" *)
  input clk;
  wire clk;
  (* src = "tt_um_cejmu.sv:14.24-14.27" *)
  input ena;
  wire ena;
  (* src = "tt_um_cejmu.sv:21.24-21.35" *)
  wire [7:0] project_mux;
  (* src = "tt_um_cejmu.sv:27.31-27.36" *)
  wire [16:0] rca_z;
  (* src = "tt_um_cejmu.sv:22.24-22.27" *)
  wire rst;
  (* src = "tt_um_cejmu.sv:16.24-16.29" *)
  input rst_n;
  wire rst_n;
  (* src = "tt_um_cejmu.sv:24.24-24.34" *)
  wire [7:0] serdes_out;
  (* src = "tt_um_cejmu.sv:9.24-9.29" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "tt_um_cejmu.sv:11.24-11.30" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "tt_um_cejmu.sv:13.24-13.30" *)
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  (* src = "tt_um_cejmu.sv:12.24-12.31" *)
  output [7:0] uio_out;
  wire [7:0] uio_out;
  (* src = "tt_um_cejmu.sv:10.24-10.30" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  assign _03_ = uio_in[1:0] == (* src = "tt_um_cejmu.sv:75.26-75.46" *) 2'h2;
  assign _04_ = ! (* src = "tt_um_cejmu.sv:51.18-51.24" *) rst_n;
  function [7:0] _13_;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "tt_um_cejmu.sv:0.0-0.0|tt_um_cejmu.sv:31.9-38.16" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _13_ = b[7:0];
      3'b?1?:
        _13_ = b[15:8];
      3'b1??:
        _13_ = b[23:16];
      default:
        _13_ = a;
    endcase
  endfunction
  assign _05_ = _13_(ui_in, { 7'h00, bav0_out, serdes_out, serdes_out }, { _08_, _07_, _06_ });
  assign _06_ = uio_in[1:0] == (* full_case = 32'd1 *) (* src = "tt_um_cejmu.sv:0.0-0.0|tt_um_cejmu.sv:31.9-38.16" *) 2'h3;
  assign _07_ = uio_in[1:0] == (* full_case = 32'd1 *) (* src = "tt_um_cejmu.sv:0.0-0.0|tt_um_cejmu.sv:31.9-38.16" *) 2'h2;
  assign _08_ = ! (* full_case = 32'd1 *) (* src = "tt_um_cejmu.sv:0.0-0.0|tt_um_cejmu.sv:31.9-38.16" *) uio_in[1:0];
  assign _10_ = _03_ ? (* src = "tt_um_cejmu.sv:75.25-75.63" *) rca_z : cla_z;
  (* module_not_derived = 32'd1 *)
  (* src = "tt_um_cejmu.sv:56.14-61.6" *)
  baverage bav0 (
    .clk(clk),
    .rst(rst),
    .x(ui_in[1:0]),
    .y(bav0_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "tt_um_cejmu.sv:77.18-81.6" *)
  \$paramod\cla\WIDTH=s32'00000000000000000000000000010000  cla (
    .a(add_a),
    .b(add_b),
    .z(cla_z)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "tt_um_cejmu.sv:63.24-73.6" *)
  \$paramod\io_serdes\WIDTH=s32'00000000000000000000000000010000  io_sd (
    .a(add_a),
    .b(add_b),
    .clk(clk),
    .inputs(ui_in),
    .output_result(uio_in[3]),
    .outputs(serdes_out),
    .reset(rst_n),
    .start_calc(uio_in[2]),
    .z(add_result[15:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "tt_um_cejmu.sv:83.18-87.6" *)
  \$paramod\rca\WIDTH=s32'00000000000000000000000000010000  rca (
    .a(add_a),
    .b(add_b),
    .s(rca_z)
  );
  assign uo_out = project_mux;
  assign uio_oe = 8'hc0;
  assign uio_out[7] = cla_z[16];
  assign uio_out[6] = rca_z[16];
  assign uio_out[5:0] = 6'h00;
  assign rst = _04_;
  assign add_result = _10_;
  assign _00_ = _09_;
  assign _01_ = _02_;
  assign _02_ = _05_;
  assign _unused = _09_;
  assign project_mux = _05_;
  assign _09_ = 1'h0;
endmodule
