/* Generated by Yosys 0.36 (git sha1 cc31c6e, g++ 12.2.0 -fstack-clash-protection -mtune=generic -O2 -ffile-prefix-map=/builddir/yosys-0.36=. -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "tt_um_cejmu.sv:8.1-38.10" *)
module tt_um_cejmu(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  reg \$auto$verilog_backend.cc:2189:dump_module$6  = 0;
  (* src = "tt_um_cejmu.sv:36.9-36.43" *)
  reg _0_;
  (* src = "tt_um_cejmu.sv:0.0-0.0" *)
  reg [7:0] _1_;
  (* src = "tt_um_cejmu.sv:0.0-0.0" *)
  reg [7:0] _2_;
  (* src = "tt_um_cejmu.sv:23.38-23.51" *)
  wire [7:0] _3_;
  (* src = "tt_um_cejmu.sv:36.19-36.43" *)
  wire _4_;
  (* src = "tt_um_cejmu.sv:24.38-24.51" *)
  wire [7:0] _5_;
  (* src = "tt_um_cejmu.sv:36.9-36.16" *)
  reg _unused;
  (* src = "tt_um_cejmu.sv:15.24-15.27" *)
  input clk;
  wire clk;
  (* src = "tt_um_cejmu.sv:14.24-14.27" *)
  input ena;
  wire ena;
  (* src = "tt_um_cejmu.sv:19.24-19.35" *)
  reg [7:0] project_mux;
  (* src = "tt_um_cejmu.sv:16.24-16.29" *)
  input rst_n;
  wire rst_n;
  (* src = "tt_um_cejmu.sv:9.24-9.29" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "tt_um_cejmu.sv:11.24-11.30" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "tt_um_cejmu.sv:13.24-13.30" *)
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  (* src = "tt_um_cejmu.sv:12.24-12.31" *)
  output [7:0] uio_out;
  wire [7:0] uio_out;
  (* src = "tt_um_cejmu.sv:10.24-10.30" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  assign _3_ = ui_in + (* src = "tt_um_cejmu.sv:23.38-23.51" *) ui_in;
  assign _4_ = & (* src = "tt_um_cejmu.sv:36.19-36.43" *) { ena, clk, rst_n, 1'h0 };
  assign _5_ = ui_in - (* src = "tt_um_cejmu.sv:24.38-24.51" *) ui_in;
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$6 ) begin end
    _1_ = _2_;
    (* src = "tt_um_cejmu.sv:22.9-27.16" *)
    casez (uio_in)
      /* src = "tt_um_cejmu.sv:0.0-0.0" */
      8'h00:
          _2_ = _3_;
      /* src = "tt_um_cejmu.sv:0.0-0.0" */
      8'h01:
          _2_ = _5_;
      /* src = "tt_um_cejmu.sv:0.0-0.0" */
      default:
          _2_ = ui_in;
    endcase
  end
  always @* begin
      project_mux <= _1_;
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$6 ) begin end
    _0_ = _4_;
  end
  always @* begin
      _unused <= _0_;
  end
  initial begin
  end
  assign uo_out = project_mux;
  assign uio_out = 8'h00;
  assign uio_oe = 8'h00;
endmodule
